//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ssprea_nvidia_control.Lang {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ssprea-nvidia-control.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string TextPowerLimit {
            get {
                return ResourceManager.GetString("TextPowerLimit", resourceCulture);
            }
        }
        
        public static string TextTemps {
            get {
                return ResourceManager.GetString("TextTemps", resourceCulture);
            }
        }
        
        public static string TextMemoryStats {
            get {
                return ResourceManager.GetString("TextMemoryStats", resourceCulture);
            }
        }
        
        public static string TextNvidiaDriverVersion {
            get {
                return ResourceManager.GetString("TextNvidiaDriverVersion", resourceCulture);
            }
        }
        
        public static string ProfilesSection {
            get {
                return ResourceManager.GetString("ProfilesSection", resourceCulture);
            }
        }
        
        public static string CheckboxStartupProfile {
            get {
                return ResourceManager.GetString("CheckboxStartupProfile", resourceCulture);
            }
        }
        
        public static string CheckboxDefaultProfile {
            get {
                return ResourceManager.GetString("CheckboxDefaultProfile", resourceCulture);
            }
        }
        
        public static string ButtonLoadToTuner {
            get {
                return ResourceManager.GetString("ButtonLoadToTuner", resourceCulture);
            }
        }
        
        public static string ButtonDeleteProfile {
            get {
                return ResourceManager.GetString("ButtonDeleteProfile", resourceCulture);
            }
        }
        
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        public static string ButtonApply {
            get {
                return ResourceManager.GetString("ButtonApply", resourceCulture);
            }
        }
        
        public static string ButtonNew {
            get {
                return ResourceManager.GetString("ButtonNew", resourceCulture);
            }
        }
        
        public static string ButtonEdit {
            get {
                return ResourceManager.GetString("ButtonEdit", resourceCulture);
            }
        }
        
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        public static string ButtonReset {
            get {
                return ResourceManager.GetString("ButtonReset", resourceCulture);
            }
        }
        
        public static string SelectGpu {
            get {
                return ResourceManager.GetString("SelectGpu", resourceCulture);
            }
        }
        
        public static string InfoSection {
            get {
                return ResourceManager.GetString("InfoSection", resourceCulture);
            }
        }
        
        public static string TunerSection {
            get {
                return ResourceManager.GetString("TunerSection", resourceCulture);
            }
        }
        
        public static string FanCurveSection {
            get {
                return ResourceManager.GetString("FanCurveSection", resourceCulture);
            }
        }
        
        public static string CurrentPstate {
            get {
                return ResourceManager.GetString("CurrentPstate", resourceCulture);
            }
        }
        
        public static string CurrentPowerLimit {
            get {
                return ResourceManager.GetString("CurrentPowerLimit", resourceCulture);
            }
        }
        
        public static string CurrentTemp {
            get {
                return ResourceManager.GetString("CurrentTemp", resourceCulture);
            }
        }
        
        public static string CurrentMemoryStats {
            get {
                return ResourceManager.GetString("CurrentMemoryStats", resourceCulture);
            }
        }
        
        public static string CurrentNvidiaDriverVersion {
            get {
                return ResourceManager.GetString("CurrentNvidiaDriverVersion", resourceCulture);
            }
        }
        
        public static string TunerCoreOffset {
            get {
                return ResourceManager.GetString("TunerCoreOffset", resourceCulture);
            }
        }
        
        public static string TunerMemoryOffset {
            get {
                return ResourceManager.GetString("TunerMemoryOffset", resourceCulture);
            }
        }
        
        public static string TunerPowerLimit {
            get {
                return ResourceManager.GetString("TunerPowerLimit", resourceCulture);
            }
        }
        
        public static string CheckboxEnableFanCurve {
            get {
                return ResourceManager.GetString("CheckboxEnableFanCurve", resourceCulture);
            }
        }
        
        public static string TooltipApplicationSettings {
            get {
                return ResourceManager.GetString("TooltipApplicationSettings", resourceCulture);
            }
        }
        
        public static string TooltipExtraGpuInfo {
            get {
                return ResourceManager.GetString("TooltipExtraGpuInfo", resourceCulture);
            }
        }
        
        public static string TooltipUsageGraphs {
            get {
                return ResourceManager.GetString("TooltipUsageGraphs", resourceCulture);
            }
        }
        
        public static string TooltipGuide {
            get {
                return ResourceManager.GetString("TooltipGuide", resourceCulture);
            }
        }
        
        public static string TooltipSaveAutoApplyProfile {
            get {
                return ResourceManager.GetString("TooltipSaveAutoApplyProfile", resourceCulture);
            }
        }
        
        public static string TooltipSaveStartupProfile {
            get {
                return ResourceManager.GetString("TooltipSaveStartupProfile", resourceCulture);
            }
        }
        
        public static string TooltipSaveAsProfile {
            get {
                return ResourceManager.GetString("TooltipSaveAsProfile", resourceCulture);
            }
        }
        
        public static string WatermarkNewProfileName {
            get {
                return ResourceManager.GetString("WatermarkNewProfileName", resourceCulture);
            }
        }
        
        public static string TextCurrent {
            get {
                return ResourceManager.GetString("TextCurrent", resourceCulture);
            }
        }
        
        public static string TextMin {
            get {
                return ResourceManager.GetString("TextMin", resourceCulture);
            }
        }
        
        public static string TextMax {
            get {
                return ResourceManager.GetString("TextMax", resourceCulture);
            }
        }
        
        public static string TextThrottle {
            get {
                return ResourceManager.GetString("TextThrottle", resourceCulture);
            }
        }
        
        public static string TextSlowdown {
            get {
                return ResourceManager.GetString("TextSlowdown", resourceCulture);
            }
        }
        
        public static string TextShutdown {
            get {
                return ResourceManager.GetString("TextShutdown", resourceCulture);
            }
        }
        
        public static string TextFree {
            get {
                return ResourceManager.GetString("TextFree", resourceCulture);
            }
        }
        
        public static string TextOutOf {
            get {
                return ResourceManager.GetString("TextOutOf", resourceCulture);
            }
        }
        
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        public static string SettingsSubtitle {
            get {
                return ResourceManager.GetString("SettingsSubtitle", resourceCulture);
            }
        }
        
        public static string SettingsSelectedGui {
            get {
                return ResourceManager.GetString("SettingsSelectedGui", resourceCulture);
            }
        }
        
        public static string SettingsSelectedGuiWarning {
            get {
                return ResourceManager.GetString("SettingsSelectedGuiWarning", resourceCulture);
            }
        }
        
        public static string GraphsCoreClock {
            get {
                return ResourceManager.GetString("GraphsCoreClock", resourceCulture);
            }
        }
        
        public static string GraphsMemClock {
            get {
                return ResourceManager.GetString("GraphsMemClock", resourceCulture);
            }
        }
        
        public static string GraphsCoreUsage {
            get {
                return ResourceManager.GetString("GraphsCoreUsage", resourceCulture);
            }
        }
        
        public static string GraphsMemUsage {
            get {
                return ResourceManager.GetString("GraphsMemUsage", resourceCulture);
            }
        }
        
        public static string GraphsCoreTemp {
            get {
                return ResourceManager.GetString("GraphsCoreTemp", resourceCulture);
            }
        }
        
        public static string GraphsFanSpeed {
            get {
                return ResourceManager.GetString("GraphsFanSpeed", resourceCulture);
            }
        }
        
        public static string GraphsGpuPower {
            get {
                return ResourceManager.GetString("GraphsGpuPower", resourceCulture);
            }
        }
        
        public static string SettingsSelectedLang {
            get {
                return ResourceManager.GetString("SettingsSelectedLang", resourceCulture);
            }
        }
        
        public static string SettingsSelectedLangWarning {
            get {
                return ResourceManager.GetString("SettingsSelectedLangWarning", resourceCulture);
            }
        }
        
        public static string TextCurrentFanSpeed {
            get {
                return ResourceManager.GetString("TextCurrentFanSpeed", resourceCulture);
            }
        }
        
        public static string TextCurrentTemp {
            get {
                return ResourceManager.GetString("TextCurrentTemp", resourceCulture);
            }
        }
        
        public static string SettingUpdateTimeDescription {
            get {
                return ResourceManager.GetString("SettingUpdateTimeDescription", resourceCulture);
            }
        }
    }
}
