<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>sspreaNvidiaControlCli</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsWindows Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Windows)))' == 'true'">true</IsWindows>
        <IsLinux Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Linux)))' == 'true'">true</IsLinux>
        <AnalysisLevel>latest-recommended</AnalysisLevel>

    </PropertyGroup>

    <PropertyGroup Condition="'$(IsWindows)'=='true'">
        <DefineConstants>WINDOWS</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="'$(IsLinux)'=='true'">
        <DefineConstants>LINUX</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <Optimize>true</Optimize>
    </PropertyGroup>

    
    
    
    
    <ItemGroup>
      <PackageReference Include="Grpc.Net.Client" Version="2.83.0" />
      <PackageReference Include="Grpc.Net.Common" Version="2.83.0" />
      <PackageReference Include="McMaster.Extensions.CommandLineUtils" Version="5.1.0" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="11.0.0-rc.1.26425.128" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
      <PackageReference Include="Serilog" Version="4.4.0" />
      <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
      <PackageReference Include="Serilog.Sinks.File" Version="8.0.0-dev-02318" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\GpuSSharp\GpuSSharp.csproj" />
      <ProjectReference Include="..\SLimit.Contracts\SLimit.Contracts.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Grpc.Net.Client">
        <HintPath>..\..\..\..\..\..\..\..\..\home\giono\.nuget\packages\grpc.net.client\2.83.0\lib\net10.0\Grpc.Net.Client.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
